### ISSUE TITLE
data/monad package not found

### ISSUE THREAD

**Issue by criptik** [martindemello/exolve-editor#1]
When attempting to run the gracket exolve-editor.rkt, consistently get package data/monad not found.
Tried raco pkg install monad which did something but still same error.

How to resolve this?  I am obviously not familiar with racket :)

**Comment by martindemello** [comment]
sorry, i should have documented that better! you need to run
```
$ raco pkg install functional-lib
```

also i've not been keeping this updated so if it has issues with the latest version of qxw do let me know.

**Comment by martindemello** [comment]
[pangrid](https://github.com/martindemello/pangrid) is a lot more up-to-date btw, since i use that regularly to convert from qxw to exolve. also check out [exet](https://viresh-ratnakar.github.io/exet.html), a construction tool from the author of exolve, which can save in exolve format directly.

**Comment by criptik** [comment]
Martin --

I did try pangrid, is this the proper behavior?

I used:  ./pangrid -f qxw -t exolve-filled -i ./senses.qxw  -o
./senses.exolve
and senses.exolve contained the grid but no light answers.  I thought it
would seed with the lights?

-- Tom

exolve-begin
  exolve-id: replace-with-unique-id
  exolve-width: 15
  exolve-height: 15
  exolve-grid:
    0000.00000.0000
    0000.00000.0000
    0000.00000.0000
    00000.000.00000
    ...000000.00000
    0000000.000....
    000.000..000000
    000.0000000.000
    000000..000.000
    ....000.0000000
    00000.000000...
    00000.000.00000
    0000.00000.0000
    0000.00000.0000
    0000.00000.0000
  exolve-across:
     1 [....]
     5 [.....]
    10 [....]
    14 [....]
    15 [.....]
    16 [....]
    17 [....]
    18 [.....]
    19 [....]
    20 [.....]
    22 [...]
    23 [.....]
    24 [......]
    26 [.....]
    27 [.......]
    30 [...]
    32 [...]
    33 [...]
    34 [......]
    38 [...]
    39 [.......]
    41 [...]
    42 [......]
    43 [...]
    44 [...]
    45 [...]
    47 [.......]
    49 [.....]
    53 [......]
    55 [.....]
    56 [...]
    57 [.....]
    61 [....]
    62 [.....]
    64 [....]
    65 [....]
    66 [.....]
    67 [....]
    68 [....]
    69 [.....]
    70 [....]
  exolve-down:
     1 [....]
     2 [....]
     3 [....]
     4 [......]
     5 [...]
     6 [........]
     7 [.....]
     8 [......]
     9 [...]
    10 [.....]
    11 [.....]
    12 [.....]
    13 [.....]
    21 [.........]
    23 [.........]
    25 [......]
    27 [....]
    28 [....]
    29 [....]
    31 [......]
    35 [....]
    36 [....]
    37 [....]
    40 [........]
    46 [......]
    48 [......]
    49 [.....]
    50 [.....]
    51 [.....]
    52 [.....]
    54 [.....]
    58 [....]
    59 [....]
    60 [....]
    62 [...]
    63 [...]
exolve-end

**Comment by martindemello** [comment]
check if you're running pangrid 0.5.3, I pushed that yesterday and it has some fixes for qxw reading. if that doesn't work, could you file a bug with pangrid and attach your qxw file?

**Comment by criptik** [comment]
Yes, that improved things.  Thanks.
